#!/usr/bin/env python3
import codecs
import os

PROJECT_BASE = os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')
PROJECT_DATA = os.path.join(PROJECT_BASE, 'data')
PROJECT_SRC  = os.path.join(PROJECT_BASE, 'src')

SCRIPT = os.path.relpath(os.path.realpath(__file__), PROJECT_BASE)

CP950  = os.path.join(PROJECT_DATA, 'cp950', 'cp950-b2u.txt')
UAO241 = os.path.join(PROJECT_DATA, 'uao', 'uao241-b2u.txt')
UAO250 = os.path.join(PROJECT_DATA, 'uao', 'uao250-b2u.txt')

OUTPUT_HEADER = os.path.join(PROJECT_SRC, 'uao_table.h')

def to_utf8_string(unicode_):
    return codecs.encode(chr(unicode_), 'UTF-8')

def to_big5_string(big5):
    if big5 // 0x100:
        return bytes([big5 // 0x100, big5 % 0x100])
    return bytes([big5])

def main():
    b2u_common = {}
    b2u_uao241 = {}
    b2u_uao250 = {}

    with open(CP950) as f:
        for l in f:
            if l.startswith('#'):
                continue
            (big5, unicode_) = map(lambda x: int(x, 0), l.split(' '))

            big5 = to_big5_string(big5)
            utf8 = to_utf8_string(unicode_)

            b2u_common[big5] = utf8

    with open(UAO241) as f:
        for l in f:
            if l.startswith('#'):
                continue
            (big5, unicode_) = map(lambda x: int(x, 0), l.split(' '))

            big5 = to_big5_string(big5)
            utf8 = to_utf8_string(unicode_)

            b2u_uao241[big5] = utf8

    with open(UAO250) as f:
        for l in f:
            if l.startswith('#'):
                continue
            (big5, unicode_) = map(lambda x: int(x, 0), l.split(' '))

            big5 = to_big5_string(big5)
            utf8 = to_utf8_string(unicode_)

            if big5 in b2u_uao241 and b2u_uao241[big5] == utf8:
                b2u_common[big5] = utf8
                del b2u_uao241[big5]
            else:
                b2u_uao250[big5] = utf8

    with open(OUTPUT_HEADER, 'w') as f:
        print('// Generated by {}'.format(SCRIPT), file=f)
        content = '''
#pragma once

enum {
    UTF8_SIZE = 4,
    BIG5_SIZE = 2,
};

struct Big5_UTF8_Table {
    unsigned char utf8[UTF8_SIZE];
    unsigned char big5[BIG5_SIZE];
};
        '''
        print(content, file=f)

        print('struct Big5_UTF8_Table BIG5_TO_UTF8_COMMON[] = {', file=f)
        print('};', file=f)

        print('struct Big5_UTF8_Table UTF8_TO_BIG5_COMMON[] = {', file=f)
        print('};', file=f)

        print('struct Big5_UTF8_Table BIG5_TO_UTF8_UAO241[] = {', file=f)
        print('};', file=f)

        print('struct Big5_UTF8_Table UTF8_TO_BIG5_UAO241[] = {', file=f)
        print('};', file=f)

        print('struct Big5_UTF8_Table BIG5_TO_UTF8_UAO250[] = {', file=f)
        print('};', file=f)

        print('struct Big5_UTF8_Table UTF8_TO_BIG5_UAO250[] = {', file=f)
        print('};', file=f)

if __name__ == '__main__':
    main()
